env:
  browser: true
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
rules:
  indent:
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
